# Generated by Django 5.0.14 on 2026-06-19 18:56

import modulos.proyectos.infraestructura.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectomodel',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Imagen de portada del proyecto. Máx 5MB. Formatos: jpg, png, webp.', null=True, upload_to=modulos.proyectos.infraestructura.models.portada_upload_path),
        ),
    ]
