# Generated by Django 5.0.14 on 2026-06-20 00:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_proyectomodel_cover_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='proyectomodel',
            index=models.Index(fields=['created_at'], name='projects_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='proyectomodel',
            index=models.Index(fields=['status'], name='projects_status_idx'),
        ),
        migrations.AddIndex(
            model_name='proyectomodel',
            index=models.Index(fields=['created_by'], name='projects_created_by_idx'),
        ),
    ]
