# Generated by Django 5.0.14 on 2026-06-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_proyectomodel_projects_created_at_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectomodel',
            name='contract_object',
            field=models.TextField(blank=True, null=True),
        ),
    ]
