# Generated by Django 5.0.14 on 2026-06-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_seed_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariorolmodel',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuariorolmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
