# Generated by Django 5.0.14 on 2026-06-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_usuariorolmodel_activo_usuariorolmodel_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolmodel',
            name='tipo_alcance',
            field=models.CharField(default='proyecto', max_length=50),
        ),
    ]
