# Generated by Django 5.0.14 on 2026-06-20 23:32

from django.db import migrations, models
import uuid

def populate_codes_and_roles(apps, schema_editor):
    RolModel = apps.get_model('roles', 'RolModel')
    PermisoModel = apps.get_model('roles', 'PermisoModel')
    RolPermisoModel = apps.get_model('roles', 'RolPermisoModel')

    # Roles definitivos
    roles_definitivos = [
        {
            'codigo': 'superadministrador',
            'nombre': 'Superadministrador',
            'descripcion': 'Acceso global a toda la plataforma. Crea usuarios, roles, permisos y proyectos.',
            'tipo_alcance': 'global',
            'es_sistema': True,
            'permisos': []
        },
        {
            'codigo': 'administrador_proyecto',
            'nombre': 'Administrador de proyecto',
            'descripcion': 'Gestiona únicamente el equipo de ese proyecto.',
            'tipo_alcance': 'proyecto',
            'es_sistema': True,
            'permisos': [
                'proyectos.ver',
                'miembros.ver',
                'miembros.asignar',
                'miembros.actualizar',
                'miembros.retirar',
                'componentes.ver',
                'acciones.ver',
                'evidencias.ver'
            ]
        },
        {
            'codigo': 'coordinador_proyecto',
            'nombre': 'Coordinador de proyecto',
            'descripcion': 'Gestiona proyectos y sus componentes.',
            'tipo_alcance': 'proyecto',
            'es_sistema': True,
            'permisos': [
                'proyectos.ver',
                'componentes.ver',
                'acciones.ver',
                'evidencias.ver'
            ]
        },
        {
            'codigo': 'coordinador_componente',
            'nombre': 'Coordinador de componente',
            'descripcion': 'Gestiona acciones, metas y verificadores.',
            'tipo_alcance': 'componente',
            'es_sistema': True,
            'permisos': [
                'proyectos.ver',
                'componentes.ver',
                'acciones.ver',
                'evidencias.ver'
            ]
        },
        {
            'codigo': 'profesional_carga',
            'nombre': 'Profesional de carga',
            'descripcion': 'Carga evidencias en acciones asignadas.',
            'tipo_alcance': 'proyecto',
            'es_sistema': True,
            'permisos': [
                'proyectos.ver',
                'componentes.ver',
                'acciones.ver',
                'evidencias.ver'
            ]
        },
        {
            'codigo': 'verificador',
            'nombre': 'Verificador',
            'descripcion': 'Aprueba o rechaza evidencias.',
            'tipo_alcance': 'proyecto',
            'es_sistema': True,
            'permisos': [
                'proyectos.ver',
                'componentes.ver',
                'acciones.ver',
                'evidencias.ver'
            ]
        },
        {
            'codigo': 'direccion_consulta',
            'nombre': 'Dirección consulta',
            'descripcion': 'Consulta información y reportes.',
            'tipo_alcance': 'proyecto',
            'es_sistema': True,
            'permisos': [
                'proyectos.ver',
                'componentes.ver',
                'acciones.ver',
                'evidencias.ver'
            ]
        },
        {
            'codigo': 'consulta_publica',
            'nombre': 'Consulta pública',
            'descripcion': 'Acceso de consulta pública.',
            'tipo_alcance': 'publico',
            'es_sistema': True,
            'permisos': [
                'proyectos.ver'
            ]
        }
    ]

    for r_def in roles_definitivos:
        rol_obj = RolModel.objects.filter(nombre=r_def['nombre']).first()
        if rol_obj:
            rol_obj.codigo = r_def['codigo']
            rol_obj.descripcion = r_def['descripcion']
            rol_obj.tipo_alcance = r_def['tipo_alcance']
            rol_obj.es_sistema = r_def['es_sistema']
            rol_obj.save()
        else:
            rol_obj = RolModel.objects.create(
                codigo=r_def['codigo'],
                nombre=r_def['nombre'],
                descripcion=r_def['descripcion'],
                tipo_alcance=r_def['tipo_alcance'],
                es_sistema=r_def['es_sistema'],
                activo=True
            )

        if r_def['permisos']:
            RolPermisoModel.objects.filter(rol=rol_obj).delete()
            for perm_cod in r_def['permisos']:
                perm_obj = PermisoModel.objects.filter(codigo=perm_cod).first()
                if not perm_obj:
                    parts = perm_cod.split('.')
                    mod = parts[0] if len(parts) > 1 else 'general'
                    perm_obj = PermisoModel.objects.create(
                        codigo=perm_cod,
                        nombre=perm_cod.replace('.', ' ').capitalize(),
                        modulo=mod
                    )
                RolPermisoModel.objects.get_or_create(rol=rol_obj, permiso=perm_obj)

    for rol_obj in RolModel.objects.filter(codigo=''):
        slug = rol_obj.nombre.lower().replace(' ', '_')
        if RolModel.objects.filter(codigo=slug).exists():
            slug = f"{slug}_{uuid.uuid4().hex[:6]}"
        rol_obj.codigo = slug
        rol_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0005_update_role_scopes'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolmodel',
            name='codigo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.RunPython(populate_codes_and_roles),
        migrations.AlterField(
            model_name='rolmodel',
            name='codigo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
