# Generated by Django 5.0.14 on 2026-06-20 23:57

from django.conf import settings
from django.db import migrations, models

def deduplicate_active_roles(apps, schema_editor):
    UsuarioRolModel = apps.get_model('roles', 'UsuarioRolModel')
    # Buscar todas las asignaciones activas vinculadas a un proyecto
    active_assignments = UsuarioRolModel.objects.filter(activo=True, proyecto__isnull=False)
    
    # Agrupar por (usuario, proyecto)
    from collections import defaultdict
    groups = defaultdict(list)
    for asig in active_assignments:
        groups[(asig.usuario_id, asig.proyecto_id)].append(asig)
        
    for (usr_id, proj_id), asigs in groups.items():
        if len(asigs) > 1:
            # Ordenar por el más reciente
            asigs.sort(key=lambda x: x.created_at, reverse=True)
            # El primero queda activo, todos los demás se desactivan
            for old_asig in asigs[1:]:
                old_asig.activo = False
                old_asig.save()

class Migration(migrations.Migration):

    dependencies = [
        ('acciones', '0001_initial'),
        ('componentes', '0001_initial'),
        ('proyectos', '0003_proyectomodel_projects_created_at_idx_and_more'),
        ('roles', '0006_rolmodel_codigo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(deduplicate_active_roles, elidable=True),
        migrations.AddConstraint(
            model_name='usuariorolmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('usuario', 'proyecto'), name='unique_active_user_role_per_project'),
        ),
    ]
