# Generated by Django 5.0.14 on 2026-06-21 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acciones', '0001_initial'),
        ('componentes', '0002_componentemodel_meta'),
        ('proyectos', '0003_proyectomodel_projects_created_at_idx_and_more'),
        ('roles', '0008_update_permissions_ticket59'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usuariorolmodel',
            name='unique_active_user_role_per_project',
        ),
        migrations.AddConstraint(
            model_name='usuariorolmodel',
            constraint=models.UniqueConstraint(fields=('usuario', 'rol', 'proyecto', 'componente', 'accion', 'activo'), name='unique_usuario_rol_proyecto_componente_accion_activo', nulls_distinct=False),
        ),
    ]
