# Generated by Django 5.0.14 on 2026-06-20 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/fotos/'),
        ),
    ]
