# Generated by Django 5.0.14 on 2026-06-21 00:13

from django.db import migrations, models

def split_existing_names(apps, schema_editor):
    ProfileModel = apps.get_model('autenticacion', 'ProfileModel')
    for perfil in ProfileModel.objects.select_related('user').all():
        user = perfil.user
        
        # first_name -> primer_nombre, segundo_nombre
        first_name = user.first_name.strip() if user.first_name else ""
        if not first_name:
            first_name = user.username
            
        parts_first = first_name.split(maxsplit=1)
        perfil.primer_nombre = parts_first[0][:80]
        if len(parts_first) > 1:
            perfil.segundo_nombre = parts_first[1][:80]
            
        # last_name -> primer_apellido, segundo_apellido
        last_name = user.last_name.strip() if user.last_name else ""
        if not last_name:
            perfil.primer_apellido = "Respaldo"
        else:
            parts_last = last_name.split(maxsplit=1)
            perfil.primer_apellido = parts_last[0][:80]
            if len(parts_last) > 1:
                perfil.segundo_apellido = parts_last[1][:80]
                
        perfil.save()

class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_profilemodel_cedula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='primer_apellido',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='primer_nombre',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.RunPython(split_existing_names, elidable=True),
    ]
