# Generated by Django 5.0.14 on 2026-06-21 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0001_initial'),
        ('metas', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentemodel',
            name='meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='metas.metamodel'),
        ),
    ]
