# Generated by Django 5.0.14 on 2026-06-21 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0003_migrate_components_to_default_meta'),
        ('metas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentemodel',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='metas.metamodel'),
        ),
    ]
