import React from 'react';
import { StyleSheet } from 'react-native';
import { colors } from '../../../shared/constants/colors';
import { spacing } from '../../../shared/constants/spacing';
import { typography } from '../../../shared/constants/typography';

export const htmlInputStyle: React.CSSProperties = {
  width: '100%',
  padding: '10px 14px 10px 38px',
  borderRadius: '10px',
  border: `1px solid ${colors.border}`,
  fontSize: '13px',
  fontFamily: typography.fontFamily,
  backgroundColor: '#ffffff',
  outline: 'none',
  boxSizing: 'border-box',
};

export const htmlDateInputStyle: React.CSSProperties = {
  width: '100%',
  padding: '10px 14px',
  borderRadius: '10px',
  border: `1px solid ${colors.border}`,
  fontSize: '13px',
  fontFamily: typography.fontFamily,
  backgroundColor: '#ffffff',
  outline: 'none',
  boxSizing: 'border-box',
};

export const htmlSelectStyle: React.CSSProperties = {
  width: '100%',
  padding: '10px 32px 10px 14px',
  borderRadius: '10px',
  border: `1px solid ${colors.border}`,
  fontSize: '13px',
  fontFamily: typography.fontFamily,
  backgroundColor: '#ffffff',
  outline: 'none',
  boxSizing: 'border-box',
  cursor: 'pointer',
  appearance: 'none',
};

export const htmlPageSelectStyle: React.CSSProperties = {
  padding: '4px 8px',
  borderRadius: '6px',
  border: `1px solid ${colors.border}`,
  fontSize: '12px',
  fontFamily: typography.fontFamily,
  backgroundColor: '#ffffff',
  cursor: 'pointer',
  marginLeft: '6px',
};

export const htmlTextAreaStyle: React.CSSProperties = {
  width: '100%',
  minHeight: '80px',
  padding: '12px',
  borderRadius: '10px',
  border: `1px solid ${colors.border}`,
  fontSize: '13px',
  fontFamily: typography.fontFamily,
  backgroundColor: '#ffffff',
  outline: 'none',
  boxSizing: 'border-box',
  resize: 'vertical',
};


export const styles = StyleSheet.create({
  shell: {
    backgroundColor: '#f8fafc',
    alignSelf: 'stretch' as any,
  },
  loader: {
    marginTop: 64,
  },
  btnVolver: {
    marginTop: spacing.md,
    alignSelf: 'center',
    paddingVertical: 10,
    paddingHorizontal: 20,
    backgroundColor: colors.primary,
    borderRadius: 8,
  },
  btnVolverText: {
    color: '#ffffff',
    fontFamily: typography.fontFamily,
    fontWeight: 'bold',
  },
  header: {
    marginBottom: spacing.md,
    alignSelf: 'stretch' as any,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: '#f1f5f9',
    alignSelf: 'flex-start',
    marginBottom: spacing.xs,
  } as any,
  backButtonText: {
    fontFamily: typography.fontFamily,
    fontSize: typography.sizes.sm,
    color: colors.primary,
    fontWeight: '700',
  },
  headerTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  } as any,
  title: {
    fontFamily: typography.fontFamily,
    fontSize: 22,
    fontWeight: '800',
    color: '#0f172a',
  },
  subtitle: {
    fontFamily: typography.fontFamily,
    fontSize: typography.sizes.sm,
    color: '#64748b',
    marginTop: 2,
  },
  cleanBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: colors.primary,
    paddingVertical: 7,
    paddingHorizontal: 14,
    borderRadius: 20,
    backgroundColor: '#ffffff',
  } as any,
  cleanBtnText: {
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '700',
    color: colors.primary,
  },
  pdfBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.primary,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 20,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 2,
  } as any,
  pdfBtnText: {
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '700',
    color: '#ffffff',
  },
  filtersCard: {
    padding: spacing.md,
    marginBottom: spacing.md,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#ffffff',
    alignSelf: 'stretch' as any,
    width: '100%',
    zIndex: 50,
    position: 'relative',
  },

  filtersHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
    paddingBottom: spacing.xs,
  } as any,
  filtersTitle: {
    fontFamily: typography.fontFamily,
    fontSize: typography.sizes.sm,
    fontWeight: '700',
    color: '#334155',
  },
  filtersGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  } as any,
  filterGroup: {
    gap: 4,
  } as any,
  filterLabel: {
    fontFamily: typography.fontFamily,
    fontSize: 11,
    fontWeight: '600',
    color: '#64748b',
  },
  inputWrapper: {
    position: 'relative',
    width: '100%',
  },
  inputIcon: {
    position: 'absolute',
    left: 12,
    top: 11,
    zIndex: 1,
  },
  selectWrapper: {
    position: 'relative',
    width: '100%',
  },
  selectArrow: {
    position: 'absolute',
    right: 12,
    top: 12,
    pointerEvents: 'none',
  } as any,
  tableCard: {
    padding: 0,
    borderRadius: 16,
    overflow: 'hidden' as any,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#ffffff',
    alignSelf: 'stretch' as any,
    width: '100%',
  },
  emptyContainer: {
    alignItems: 'center',
    paddingVertical: 56,
    gap: 8,
  } as any,
  emptyText: {
    fontFamily: typography.fontFamily,
    fontSize: typography.sizes.sm,
    color: '#64748b',
    fontStyle: 'italic',
  },
  tableContainer: {
    width: '100%',
  },
  tableHeaderRow: {
    flexDirection: 'row',
    backgroundColor: '#f8fafc',
    borderBottomWidth: 2,
    borderBottomColor: '#e2e8f0',
    paddingVertical: 14,
    paddingHorizontal: 16,
    alignItems: 'center',
  } as any,
  th: {
    fontFamily: typography.fontFamily,
    fontSize: 11,
    fontWeight: '700',
    color: '#475569',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  rowContainer: {
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  tableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    backgroundColor: '#ffffff',
  } as any,
  tableRowActive: {
    backgroundColor: 'rgba(108,85,201,0.02)',
  },
  arrowCol: {
    width: 40,
    justifyContent: 'center',
    alignItems: 'flex-start',
  } as any,
  tdCol: {
    justifyContent: 'center',
  },
  td: {
    fontFamily: typography.fontFamily,
    fontSize: 13,
    color: '#334155',
  },
  avatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#e0e7ff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.primary,
    fontFamily: typography.fontFamily,
  },
  colabName: {
    fontFamily: typography.fontFamily,
    fontSize: 13,
    fontWeight: '700',
    color: '#1e293b',
  },
  colabEmail: {
    fontFamily: typography.fontFamily,
    fontSize: 10,
    color: '#64748b',
    marginTop: 1,
  },
  countBadge: {
    backgroundColor: 'rgba(108,85,201,0.1)',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 2,
    minWidth: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  countBadgeText: {
    fontFamily: typography.fontFamily,
    fontSize: 11,
    fontWeight: '700',
    color: colors.primary,
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  statusBadgeText: {
    fontFamily: typography.fontFamily,
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  reabrirBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.primary,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 12,
  } as any,
  deleteBtn: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.error,
    padding: 6,
    borderRadius: 12,
  } as any,
  actionBtnText: {
    fontFamily: typography.fontFamily,
    fontSize: 11,
    fontWeight: '700',
    color: '#ffffff',
  },
  // Collapsible inner drawer
  expandedDrawer: {
    backgroundColor: '#f8fafc',
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
    borderBottomWidth: 1,
    borderBottomColor: '#cbd5e1',
  },
  drawerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  } as any,
  drawerTitle: {
    fontFamily: typography.fontFamily,
    fontSize: 13,
    fontWeight: '800',
    color: '#1e293b',
  },
  drawerCountBadge: {
    backgroundColor: '#e2e8f0',
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  drawerCountBadgeText: {
    fontFamily: typography.fontFamily,
    fontSize: 10,
    fontWeight: '600',
    color: '#475569',
  },
  soportesList: {
    gap: 8,
  } as any,
  emptySoportesText: {
    fontFamily: typography.fontFamily,
    fontSize: 12,
    color: '#94a3b8',
    fontStyle: 'italic',
  },
  soporteRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#ffffff',
    padding: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  } as any,
  soporteIconWrapper: {
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  soporteName: {
    fontFamily: typography.fontFamily,
    fontSize: 13,
    fontWeight: '600',
    color: '#1e293b',
  },
  soporteMeta: {
    fontFamily: typography.fontFamily,
    fontSize: 10,
    color: '#64748b',
    marginTop: 2,
  },
  soporteActions: {
    flexDirection: 'row',
    gap: 6,
  } as any,
  soporteActionBtn: {
    padding: 6,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#f8fafc',
  },
  paginationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#f8fafc',
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
  } as any,
  paginationText: {
    fontFamily: typography.fontFamily,
    fontSize: 12,
    color: '#64748b',
  },
  pageSizeRow: {
    flexDirection: 'row',
    alignItems: 'center',
  } as any,
  pageSizeLabel: {
    fontFamily: typography.fontFamily,
    fontSize: 12,
    color: '#64748b',
  },
  paginationButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  } as any,
  pageBtn: {
    padding: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pageBtnDisabled: {
    backgroundColor: '#f1f5f9',
    borderColor: '#e2e8f0',
    opacity: 0.6,
  },
  pageNumberBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    backgroundColor: '#e2e8f0',
  },
  pageNumberText: {
    fontFamily: typography.fontFamily,
    fontSize: 11,
    fontWeight: '700',
    color: '#334155',
  },
  // Modal de Vista Previa
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  modalContent: {
    width: '100%',
    maxWidth: 620,
    backgroundColor: '#ffffff',
    borderRadius: 16,
    overflow: 'hidden' as any,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 8,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  } as any,
  modalTitle: {
    fontFamily: typography.fontFamily,
    fontSize: 15,
    fontWeight: '700',
    color: '#0f172a',
    flex: 1,
  },
  closeModalBtn: {
    padding: 4,
  },
  modalBody: {
    backgroundColor: '#f8fafc',
    padding: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  imagePreviewContainer: {
    width: '100%',
    height: 380,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden' as any,
    backgroundColor: '#f1f5f9',
    borderRadius: 8,
    position: 'relative',
  },
  zoomControls: {
    position: 'absolute',
    bottom: 12,
    right: 12,
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 20,
    padding: 4,
    gap: 4,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  } as any,
  zoomBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  zoomText: {
    fontFamily: typography.fontFamily,
    fontSize: 10,
    fontWeight: '700',
    color: '#334155',
    paddingHorizontal: 4,
  },
  nonImagePreview: {
    width: '100%',
    height: 380,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f8fafc',
  },
  nonImageText: {
    fontFamily: typography.fontFamily,
    fontSize: 13,
    fontWeight: '600',
    color: '#475569',
    marginTop: 12,
    textAlign: 'center',
    paddingHorizontal: 24,
  },
  nonImageSubtext: {
    fontFamily: typography.fontFamily,
    fontSize: 11,
    color: '#94a3b8',
    marginTop: 4,
  },
  modalFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
  } as any,
  modalFooterMeta: {
    fontFamily: typography.fontFamily,
    fontSize: 11,
    color: '#64748b',
  },
  modalFooterSize: {
    fontFamily: typography.fontFamily,
    fontSize: 11,
    fontWeight: '700',
    color: '#475569',
    marginTop: 2,
  },
  openTabBtn: {
    backgroundColor: colors.primary,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 8,
  },
  openTabBtnText: {
    fontFamily: typography.fontFamily,
    fontSize: 12,
    color: '#ffffff',
    fontWeight: '700',
  },
  requisitosContainer: {
    marginTop: 12,
    gap: 16,
  } as any,
  requisitoGroup: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    padding: 12,
  },
  requisitoGroupHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
    paddingBottom: 8,
    marginBottom: 12,
  } as any,
  requisitoGroupTitle: {
    fontFamily: typography.fontFamily,
    fontSize: 13,
    fontWeight: '700',
    color: '#1e293b',
  },
  requisitoGroupCount: {
    fontFamily: typography.fontFamily,
    fontSize: 11,
    color: '#64748b',
  },
  soportesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  } as any,
  soporteGridItem: {
    width: 100,
    alignItems: 'center',
    gap: 6,
  } as any,
  soportePreview: {
    width: 100,
    height: 100,
    borderRadius: 8,
    overflow: 'hidden' as any,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    position: 'relative',
    backgroundColor: '#f8fafc',
    alignItems: 'center',
    justifyContent: 'center',
  } as any,
  soporteThumbImage: {
    width: '100%',
    height: '100%',
  },
  soporteHoverOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  } as any,
  soporteHoverBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.4)',
  },
  soporteGridName: {
    fontFamily: typography.fontFamily,
    fontSize: 11,
    color: '#334155',
    textAlign: 'center',
    width: '100%',
  } as any,
  reviewPanel: {
    marginTop: 20,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#cbd5e1',
  },
  reviewPanelTitle: {
    fontFamily: typography.fontFamily,
    fontSize: 14,
    fontWeight: '700',
    color: '#0f172a',
    marginBottom: 8,
  },
  reviewCommentContainer: {
    marginBottom: 12,
  },
  reviewLabel: {
    fontFamily: typography.fontFamily,
    fontSize: 11,
    fontWeight: '600',
    color: '#475569',
    marginBottom: 6,
  },
  reviewActionsRow: {
    flexDirection: 'row',
    gap: 12,
  } as any,
  reviewBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
  } as any,
  reviewBtnAprobar: {
    backgroundColor: '#10b981',
  },
  reviewBtnObservar: {
    backgroundColor: '#f59e0b',
  },
  reviewBtnText: {
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '700',
    color: '#ffffff',
  },
  dialogOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  dialogContent: {
    width: '100%',
    maxWidth: 400,
    backgroundColor: '#ffffff',
    borderRadius: 16,
    overflow: 'hidden' as any,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 8,
  },
  dialogHeader: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  } as any,
  dialogTitle: {
    fontFamily: typography.fontFamily,
    fontSize: 16,
    fontWeight: '700',
    color: '#0f172a',
  },
  dialogBody: {
    padding: 20,
    alignItems: 'stretch' as any,
  } as any,
  dialogMessage: {
    fontFamily: typography.fontFamily,
    fontSize: 13,
    color: '#475569',
    lineHeight: 18,
  },
  dialogFooter: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
    padding: 12,
    gap: 8,
    justifyContent: 'flex-end',
  } as any,
  dialogBtn: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    minWidth: 80,
    alignItems: 'center',
  } as any,
  dialogBtnConfirm: {
    backgroundColor: colors.primary,
  },
  dialogBtnConfirmText: {
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '700',
    color: '#ffffff',
  },
  dialogBtnCancel: {
    backgroundColor: '#f1f5f9',
    borderWidth: 1,
    borderColor: '#cbd5e1',
  },
  dialogBtnCancelText: {
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '700',
    color: '#475569',
  },
});

