# Generated by Django 5.0.14 on 2026-06-21 22:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acciones', '0002_action_measurement_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitoVerificacionAccionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('obligatorio', models.BooleanField(default=True)),
                ('tipos_archivo_permitidos', models.JSONField(default=list)),
                ('min_archivos', models.PositiveIntegerField(default=1)),
                ('max_archivos', models.PositiveIntegerField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='acciones.accionmodel')),
            ],
            options={
                'db_table': 'accion_requisitos_verificacion',
                'ordering': ['orden', 'created_at'],
            },
        ),
    ]
