# Generated by Django 5.0.14 on 2026-06-22 20:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acciones', '0003_add_requisito_verificacion_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionResponsableAccionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_asignacion', models.CharField(choices=[('responsable', 'Responsable'), ('apoyo', 'Apoyo')], default='responsable', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsables', to='acciones.accionmodel')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_otorgadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_acciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accion_responsables',
            },
        ),
        migrations.CreateModel(
            name='HistorialEjecucionAccionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_ejecucion', to='acciones.accionmodel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_ejecucion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accion_historial_ejecucion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='asignacionresponsableaccionmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('accion', 'usuario'), name='unique_active_assignment'),
        ),
    ]
