# Generated by Django 5.0.14 on 2026-06-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acciones', '0005_accionmodel_tipos_evidencia_permitidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='accionmodel',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accionmodel',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
