# Generated by Django 5.0.14 on 2026-06-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acciones', '0006_accionmodel_end_date_accionmodel_start_date'),
        ('componentes', '0005_remove_component_measurement_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitoverificacionaccionmodel',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='accionmodel',
            index=models.Index(fields=['display_order'], name='action_display_order_idx'),
        ),
        migrations.AddIndex(
            model_name='accionmodel',
            index=models.Index(fields=['ejecucion_acumulada', 'proyeccion_cuantitativa'], name='action_avance_idx'),
        ),
    ]
