# Generated by Django 5.0.14 on 2026-06-26 04:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acciones', '0007_indexes_rendimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='accionmodel',
            name='requiere_grupos',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AccionGrupoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='acciones.accionmodel')),
            ],
            options={
                'db_table': 'accion_grupos',
                'ordering': ['nombre', 'created_at'],
                'indexes': [models.Index(fields=['accion', 'activo'], name='group_accion_activo_idx'), models.Index(fields=['accion', 'nombre'], name='group_accion_nombre_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='acciongrupomodel',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('accion', 'nombre'), name='unique_active_group_name'),
        ),
    ]
