# Generated by Django 5.0.14 on 2026-06-21 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acciones', '0003_add_requisito_verificacion_model'),
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='evidencias/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='uploadmodel',
            name='requisito',
            field=models.ForeignKey(blank=True, help_text='Requisito de verificación al que corresponde esta evidencia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='acciones.requisitoverificacionaccionmodel'),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='file_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='file_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
