# Generated by Django 5.0.14 on 2026-06-23 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencias', '0002_evidenciaactividadmodel'),
        ('uploads', '0003_upload_fecha_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='evidencia_actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soportes', to='evidencias.evidenciaactividadmodel'),
        ),
    ]
