# Generated by Django 5.0.14 on 2026-06-23 17:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acciones', '0004_asignacionresponsableaccionmodel_and_more'),
        ('evidencias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaActividadModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_ejecucion', models.DateField(blank=True, null=True)),
                ('cantidad_ejecutada', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('observada', 'Observada'), ('reabierta', 'Reabierta'), ('aprobada', 'Aprobada')], default='borrador', max_length=16)),
                ('observacion_coordinador', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias_operativas', to='acciones.accionmodel')),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias_actividad', to=settings.AUTH_USER_MODEL)),
                ('revisada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evidencias_actividad',
                'ordering': ['-created_at'],
            },
        ),
    ]
