# Generated by Django 5.0.14 on 2026-06-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencias', '0002_evidenciaactividadmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenciaactividadmodel',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('observada', 'Observada'), ('reabierta', 'Reabierta'), ('aprobada', 'Aprobada')], db_index=True, default='borrador', max_length=16),
        ),
    ]
