# Generated by Django 5.0.14 on 2026-06-26 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acciones', '0008_agregar_requiere_grupos_y_accion_grupos'),
        ('evidencias', '0004_indexes_rendimiento_evidencias_actividad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenciaactividadmodel',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidencias_operativas', to='acciones.acciongrupomodel'),
        ),
        migrations.AddIndex(
            model_name='evidenciaactividadmodel',
            index=models.Index(fields=['grupo', 'created_at'], name='evact_grupo_created_idx'),
        ),
    ]
