# Generated by Django 5.0.14 on 2026-06-26 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acciones', '0008_agregar_requiere_grupos_y_accion_grupos'),
        ('evidencias', '0005_agregar_grupo_a_evidencia_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenciaactividadmodel',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_operativas', to='acciones.acciongrupomodel'),
        ),
    ]
