# Generated by Django 5.0.14 on 2026-06-21 15:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0003_proyectomodel_projects_created_at_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('unidad_medida', models.CharField(max_length=100)),
                ('valor_objetivo', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metas_creadas', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='proyectos.proyectomodel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metas_actualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'metas',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['proyecto'], name='metas_proyect_769a9d_idx'), models.Index(fields=['activo'], name='metas_activo_57e7c2_idx'), models.Index(fields=['created_at'], name='metas_created_9221d6_idx')],
            },
        ),
    ]
