# Generated by Django 5.0.14 on 2026-06-19 23:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0002_proyectomodel_cover_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoMiembroModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('director', 'Director de Proyecto'), ('coordinador', 'Coordinador'), ('analista', 'Analista'), ('tecnico', 'Técnico de Campo'), ('observador', 'Observador')], default='observador', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agregado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miembros_agregados', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='proyectos.proyectomodel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_members',
                'unique_together': {('proyecto', 'usuario')},
            },
        ),
    ]
