# Generated by Django 5.0.14 on 2026-06-20 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectomiembromodel',
            name='rol',
        ),
    ]
